### PR TITLE
Add reference to Pythong bindings to README.md?

### PR DESCRIPTION
**Pull request by laurids-reichardt**
Thanks to all maintainers and contributors for their work on this great library!

Just discovered this library, but almost ended up not using it, because I assumed no Python bindings exist. That's when I discovered @LLukas22 [repo](https://github.com/LLukas22/llm-rs-python). Maybe a short reference to the Python bindings would be helpful to newcomers?

### CODE REVIEW

**Comment by danforbes** [comment]
Are there Python bindings available for the reference implementation of GGML?

**Comment by LLukas22** [comment]
There is [ctransformers](https://github.com/marella/ctransformers) which wraps the ggml examples directly and [llama-cpp-python](https://github.com/abetlen/llama-cpp-python) which wraps llama.cpp.

**Comment by danforbes** [comment]
Can we do it like this instead (sorry I'm pedantic) https://github.com/danforbes/llm/blob/docs/readme/bindings/README.md#using-llm-from-other-languages

**Comment by LLukas22** [comment]
Looks good. We should also add [llama-node](https://github.com/Atome-FE/llama-node).

**Comment by danforbes** [comment]
Thank you for your contribution! I've maintained your commit on #309 💯

**Pull request closed without merging**
