### PR TITLE
Implement MPT Model

### LINKED ISSUE #214: Support MPT
`ggml`'s had a MPT example submitted: https://github.com/ggerganov/ggml/pull/145

We should be able to support this without too much trouble.

### PR DESCRIPTION
**Pull request by danforbes**
Closes #214.

Tested with https://huggingface.co/LLukas22/mpt-7b-ggml

### CODE REVIEW

**Comment by danforbes** [comment]
I can't find a Replit model to test with.

**Comment by philpax** [comment]
This is good to go, but will produce garbage output after a few tokens without this fix to `ggml` https://github.com/ggerganov/ggml/pull/145/files#diff-b4a500ab2765c31526c5541f3e51e21e46990b87d9774cac6f3089db315bdc5b

We'll have to wait for https://github.com/ggerganov/ggml/pull/145 to be merged.

**Comment by hhamud** [comment]
65k token context here we come

**Comment by philpax** [comment]
Sounds like this is all good to go! @danforbes Does this include all of the changes from the ggml PR?

**Pull request merged**
